stages:
  - build
  - docker-build
  - docker-push
  - deploy

variables:
  # Docker 이미지 이름 변수
  DOCKER_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$DOCKER_IMAGE:$CI_COMMIT_REF_NAME .

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  
build:
  stage: build
  image: node:alpine
  script:
    # Node.js 및 npm 설치
    - apt update
    - apt install nodejs npm
  tags:
    - mis-runner

docker-build:
  stage: docker-build
  image: docker:stable
  script:
    - echo "Docker build start!!"
    # Dockerfile로 Docker 이미지 빌드
    - docker build -t $DOCKER_IMAGE .
    # Docker 이미지 푸시
    - docker push $DOCKER_IMAGE
  tags:
    - mis-runner
  dependencies:
    - build

docker-push:
  stage: docker-push
  image: docker:stable
  script:
    - echo "Docker build start!!"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    # Dockerfile로 Docker 이미지 빌드
    - docker build -t $DOCKER_IMAGE .
    # Docker 이미지 푸시
    - docker push $DOCKER_IMAGE
  tags:
    - mis-runner
  dependencies:
    - docker-build

deploy:
  stage: deploy
  script:
    # 필요 시 배포 스크립트 작성
    - echo "Deploy step"
  tags:
    - mis-runner
  dependencies:
    - docker-push